version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: test-report-db
    volumes:
      - mongo-data:/data/db
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  mongo-data:
